---
- hosts: swarm_manager
  gather_facts: no
  tasks:
    - name: Create service in swarm
      shell: "docker service create --name {{simple_service.name }} --replicas {{ simple_service.replicas }} {{ simple_service.container }} {{ simple_service.command }}"
      become: yes

    - name: Checking currently running serices
      shell: "docker services ls"
      register: services_info
      become: yes

    - debug: var=services_info

    - name: Checking sevice details
      shell: "docker service inspect {{ simple_service.name }}"
      register: service_details
      become: yes

    - debug: var=service_details

    - name: Checking sevice hosts
      shell: "docker service ps {{ simple_service.name  }}"
      register: service_hosts
      become: yes

    - debug: var=service_hosts
